stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - setsid ./ci/lint.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  artifacts:
    reports:
      codequality: lint-report.json
    expire_in: 1 week
  tags:
    - imagesbuilder

unit_test:
  stage: test
  script:
    - setsid ./ci/unit-test.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  tags:
    - imagesbuilder

integration_test:
  stage: test
  script:
    - setsid ./ci/integration-test.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  tags:
    - imagesbuilder
