stages:
  - cleanup
  - check
  - scan

cleanup_docker:
  stage: cleanup
  script:
    - ./ci/cleanup-docker.sh
  tags:
    - web
  only:
    - /^(main|develop).*$/
    - merge_requests

lint:
  stage: check
  script:
    - setsid ./ci/lint.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  artifacts:
    reports:
      codequality: lint-report.json
    expire_in: 1 week
  tags:
    - imagesbuilder

unit_test:
  stage: check
  script:
    - setsid ./ci/unit-test.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  tags:
    - imagesbuilder

integration_test:
  stage: check
  script:
    - setsid ./ci/integration-test.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  tags:
    - imagesbuilder

security:
  stage: scan
  script:
    - ./ci/security.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop.*)$/
  tags:
    - imagesbuilder
